### ISSUE TITLE
Why is this listed as a python project?

### ISSUE THREAD

**Issue by paarthtandon** [azat-co/you-dont-know-node#2]
![screenshot from 2016-04-09 13-30-23](https://cloud.githubusercontent.com/assets/8572788/14405196/42da8228-fe57-11e5-93c0-8069ace7eca0.png)

**Comment by azat-co** [comment]
@Paarthri I don't know... why not? :smile: I can't even find where you saw that. Doesn't GitHub automatically detect language?
